### PR TITLE
UWP SDK and Unit Tests Filtering

### PR DESCRIPTION
**Pull request by spottedmahn**
- add UWP Windows SDK version needed
- add a screenshot of filtering tests in VS
- add .gitignore using [VS template](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore)

Reference issue: [Build fails 'WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.CSharp.targets' was not found](https://github.com/Microsoft/testfx/issues/314)

### CODE REVIEW

**Comment by spottedmahn** [comment]
image

image

**Comment by pvlakshm** [comment]
Can you tell me more about this PR please.
Tagging @jayaranigarg.

**Comment by spottedmahn** [comment]
>add UWP Windows SDK version needed

Well, now that https://github.com/Microsoft/testfx/pull/439 is there, I need to update my PR.

This is no longer need.

>add a screenshot of filtering tests in VS

Just make it easier to read.  Show me pics, don't make me read is my philosphy!

**Comment by jayaranigarg** [comment]
@spottedmahn : We will not be able to take https://github.com/Microsoft/testfx/pull/439 as of now due to some infrastructure issues. Let's keep the PR as it is for now.

**Pull request closed without merging**
